### ISSUE TITLE
BIOS version & config

### ISSUE THREAD

**Issue by isshe** [edenpulse/Hackintosh-z370nWifi-i7-8700K-RadeonVII#1]
Hey, buddy, which version of the BIOS are you using? Can you put your BIOS configuration out?

**Comment by mbousendorfer** [comment]
Hey, using F13 as F14a is beta. 
Nothing fancy in BIOS config, it's like outlined here : [https://dortania.github.io/OpenCore-Install-Guide/config.plist/coffee-lake.html#intel-bios-settings](https://dortania.github.io/OpenCore-Install-Guide/config.plist/coffee-lake.html#intel-bios-settings)

**Comment by isshe** [comment]
Okay thanks.
